-- MySQL Script generated by MySQL Workbench
-- Wed Aug 17 15:26:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Author: Mateusz Tchorek

CREATE SCHEMA IF NOT EXISTS vlsdb;
USE vlsdb;

CREATE TABLE IF NOT EXISTS vlsdb.Login (
  Login VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NULL,
  PRIMARY KEY (Login),
  UNIQUE INDEX Login_UNIQUE (Login ASC) VISIBLE)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS vlsdb.Vocabulary (
  Id INT NOT NULL,
  Word VARCHAR(100) NULL,
  Translation VARCHAR(150) NULL,
  Language VARCHAR(45) NULL,
  User VARCHAR(255) NULL,
  PRIMARY KEY (Id),
  INDEX fk_user_login_idx (User ASC) VISIBLE,
  CONSTRAINT fk_user_login
    FOREIGN KEY (User)
    REFERENCES Login (Login)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS vlsdb.Sessions (
  Id INT NOT NULL,
  User VARCHAR(255) NULL,
  Words_amount INT NULL,
  Correct_words INT NULL,
  Learn_Type VARCHAR(45) NULL,
  Language VARCHAR(45) NULL,
  Time_Start VARCHAR(20) NULL,
  Time_Stop VARCHAR(20) NULL,
  Words_List_Id INT NULL,
  PRIMARY KEY (Id),
  INDEX fk_user_login_idx (User ASC) VISIBLE,
  CONSTRAINT fk_login_user
    FOREIGN KEY (`User`)
    REFERENCES Login (Login)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS vlsdb.Statistics (
  User VARCHAR(255) NOT NULL,
  Words INT NULL,
  Languages INT NULL,
  Progress INT NULL,
  Avg_Time INT NULL,
  Sessions INT NULL,
  Misspells INT NULL,
  PRIMARY KEY (User),
  CONSTRAINT fk_login_user_statistics
    FOREIGN KEY (User)
    REFERENCES Login (Login)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS vlsdb.Vocabulary_Sessions (
  Vocabulary_Id INT NULL,
  Session_Id INT NULL,
  INDEX fk_vocabulary_vocabulary_Id_idx (Vocabulary_Id ASC) VISIBLE,
  INDEX fk_id_session_id_idx (Session_Id ASC) VISIBLE,
  CONSTRAINT fk_id_vocabulary_Id
    FOREIGN KEY (Vocabulary_Id)
    REFERENCES Vocabulary (Id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_id_session_id
    FOREIGN KEY (Session_Id)
    REFERENCES Sessions (Id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
